# Generated by Django 3.2.4 on 2021-10-12 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travel_booking', '0004_auto_20211012_1031'),
    ]

    operations = [
        migrations.AddField(
            model_name='flight',
            name='capacity',
            field=models.IntegerField(default=None),
            preserve_default=False,
        ),
    ]
