# Generated by Django 3.2.4 on 2021-10-13 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travel_booking', '0005_flight_capacity'),
    ]

    operations = [
        migrations.AddField(
            model_name='city',
            name='imagen',
            field=models.ImageField(null=True, upload_to='destinos-image'),
        ),
    ]
