# Generated by Django 3.2.4 on 2021-10-13 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travel_booking', '0007_alter_city_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='city',
            name='description',
            field=models.CharField(default=None, max_length=150),
            preserve_default=False,
        ),
    ]
