# Generated by Django 3.2.4 on 2021-10-13 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travel_booking', '0009_alter_city_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotel',
            name='imagen',
            field=models.ImageField(null=True, upload_to='destinos-image'),
        ),
        migrations.AddField(
            model_name='hotel',
            name='name',
            field=models.CharField(default=None, max_length=30),
            preserve_default=False,
        ),
    ]
